CREATE TABLE household_demographics
  (HD_DEMO_SK NUMBER(19,0),
    HD_INCOME_BAND_SK NUMBER(19,0),
    HD_BUY_POTENTIAL VARCHAR2(4000 BYTE),
    HD_DEP_COUNT NUMBER(19,0),
    HD_VEHICLE_COUNT NUMBER(19,0))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/household_demographics/*')
  )  REJECT LIMIT UNLIMITED;


CREATE TABLE web_returns
  (WR_RETURNED_DATE_SK NUMBER(19,0),WR_RETURNED_TIME_SK NUMBER(19,0),WR_ITEM_SK NUMBER(19,0),WR_REFUNDED_CUSTOMER_SK NUMBER(19,0),WR_REFUNDED_CDEMO_SK NUMBER(19,0),WR_REFUNDED_HDEMO_SK NUMBER(19,0),WR_REFUNDED_ADDR_SK NUMBER(19,0),WR_RETURNING_CUSTOMER_SK NUMBER(19,0),WR_RETURNING_CDEMO_SK NUMBER(19,0),WR_RETURNING_HDEMO_SK NUMBER(19,0),WR_RETURNING_ADDR_SK NUMBER(19,0),WR_WEB_PAGE_SK NUMBER(19,0),WR_REASON_SK NUMBER(19,0),WR_ORDER_NUMBER NUMBER(19,0),WR_RETURN_QUANTITY NUMBER(19,0),WR_RETURN_AMT BINARY_DOUBLE,WR_RETURN_TAX BINARY_DOUBLE,WR_RETURN_AMT_INC_TAX BINARY_DOUBLE,WR_FEE BINARY_DOUBLE,WR_RETURN_SHIP_COST BINARY_DOUBLE,WR_REFUNDED_CASH BINARY_DOUBLE,WR_REVERSED_CHARGE BINARY_DOUBLE,WR_ACCOUNT_CREDIT BINARY_DOUBLE,WR_NET_LOSS BINARY_DOUBLE)
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/web_returns/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE time_dim
  (T_TIME_SK NUMBER(19,0),T_TIME_ID VARCHAR2(4000 BYTE),T_TIME NUMBER(19,0),T_HOUR NUMBER(19,0),T_MINUTE NUMBER(19,0),T_SECOND NUMBER(19,0),T_AM_PM VARCHAR2(4000 BYTE),T_SHIFT VARCHAR2(4000 BYTE),T_SUB_SHIFT VARCHAR2(4000 BYTE),T_MEAL_TIME VARCHAR2(4000 BYTE))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/time_dim/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE customer
  (C_CUSTOMER_SK NUMBER(19,0),C_CUSTOMER_ID VARCHAR2(4000 BYTE),C_CURRENT_CDEMO_SK NUMBER(19,0),C_CURRENT_HDEMO_SK NUMBER(19,0),C_CURRENT_ADDR_SK NUMBER(19,0),C_FIRST_SHIPTO_DATE_SK NUMBER(19,0),C_FIRST_SALES_DATE_SK NUMBER(19,0),C_SALUTATION VARCHAR2(4000 BYTE),C_FIRST_NAME VARCHAR2(4000 BYTE),C_LAST_NAME VARCHAR2(4000 BYTE),C_PREFERRED_CUST_FLAG VARCHAR2(4000 BYTE),C_BIRTH_DAY NUMBER(19,0),C_BIRTH_MONTH NUMBER(19,0),C_BIRTH_YEAR NUMBER(19,0),C_BIRTH_COUNTRY VARCHAR2(4000 BYTE),C_LOGIN VARCHAR2(4000 BYTE),C_EMAIL_ADDRESS VARCHAR2(4000 BYTE),C_LAST_REVIEW_DATE NUMBER(19,0))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/customer/*')
  )  REJECT LIMIT UNLIMITED;


CREATE TABLE date_dim
  (D_DATE_SK NUMBER(19,0),D_DATE_ID VARCHAR2(4000 BYTE) ,D_DATE VARCHAR2(4000 BYTE) ,D_MONTH_SEQ NUMBER(19,0),D_WEEK_SEQ NUMBER(19,0),D_QUARTER_SEQ NUMBER(19,0),D_YEAR NUMBER(19,0),D_DOW NUMBER(19,0),D_MOY NUMBER(19,0),D_DOM NUMBER(19,0),D_QOY NUMBER(19,0),D_FY_YEAR NUMBER(19,0),D_FY_QUARTER_SEQ NUMBER(19,0),D_FY_WEEK_SEQ NUMBER(19,0),D_DAY_NAME VARCHAR2(4000 BYTE) ,D_QUARTER_NAME VARCHAR2(4000 BYTE) ,D_HOLIDAY VARCHAR2(4000 BYTE) ,D_WEEKEND VARCHAR2(4000 BYTE) ,D_FOLLOWING_HOLIDAY VARCHAR2(4000 BYTE) ,D_FIRST_DOM NUMBER(19,0),D_LAST_DOM NUMBER(19,0),D_SAME_DAY_LY NUMBER(19,0),D_SAME_DAY_LQ NUMBER(19,0),D_CURRENT_DAY VARCHAR2(4000 BYTE) ,D_CURRENT_WEEK VARCHAR2(4000 BYTE) ,D_CURRENT_MONTH VARCHAR2(4000 BYTE) ,D_CURRENT_QUARTER VARCHAR2(4000 BYTE) ,D_CURRENT_YEAR VARCHAR2(4000 BYTE))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/date_dim/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE store_sales
  (SS_SOLD_DATE_SK NUMBER(19,0),SS_SOLD_TIME_SK NUMBER(19,0),SS_ITEM_SK NUMBER(19,0),SS_CUSTOMER_SK NUMBER(19,0),SS_CDEMO_SK NUMBER(19,0),SS_HDEMO_SK NUMBER(19,0),SS_ADDR_SK NUMBER(19,0),SS_STORE_SK NUMBER(19,0),SS_PROMO_SK NUMBER(19,0),SS_TICKET_NUMBER NUMBER(19,0),SS_QUANTITY NUMBER(19,0),SS_WHOLESALE_COST BINARY_DOUBLE,SS_LIST_PRICE BINARY_DOUBLE,SS_SALES_PRICE BINARY_DOUBLE,SS_EXT_DISCOUNT_AMT BINARY_DOUBLE,SS_EXT_SALES_PRICE BINARY_DOUBLE,SS_EXT_WHOLESALE_COST BINARY_DOUBLE,SS_EXT_LIST_PRICE BINARY_DOUBLE,SS_EXT_TAX BINARY_DOUBLE,SS_COUPON_AMT BINARY_DOUBLE,SS_NET_PAID BINARY_DOUBLE,SS_NET_PAID_INC_TAX BINARY_DOUBLE,SS_NET_PROFIT BINARY_DOUBLE)
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/store_sales/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE web_sales
  (WS_SOLD_DATE_SK NUMBER(19,0),WS_SOLD_TIME_SK NUMBER(19,0),WS_SHIP_DATE_SK NUMBER(19,0),WS_ITEM_SK NUMBER(19,0),WS_BILL_CUSTOMER_SK NUMBER(19,0),WS_BILL_CDEMO_SK NUMBER(19,0),WS_BILL_HDEMO_SK NUMBER(19,0),WS_BILL_ADDR_SK NUMBER(19,0),WS_SHIP_CUSTOMER_SK NUMBER(19,0),WS_SHIP_CDEMO_SK NUMBER(19,0),WS_SHIP_HDEMO_SK NUMBER(19,0),WS_SHIP_ADDR_SK NUMBER(19,0),WS_WEB_PAGE_SK NUMBER(19,0),WS_WEB_SITE_SK NUMBER(19,0),WS_SHIP_MODE_SK NUMBER(19,0),WS_WAREHOUSE_SK NUMBER(19,0),WS_PROMO_SK NUMBER(19,0),WS_ORDER_NUMBER NUMBER(19,0),WS_QUANTITY NUMBER(19,0),WS_WHOLESALE_COST BINARY_DOUBLE,WS_LIST_PRICE BINARY_DOUBLE,WS_SALES_PRICE BINARY_DOUBLE,WS_EXT_DISCOUNT_AMT BINARY_DOUBLE,WS_EXT_SALES_PRICE BINARY_DOUBLE,WS_EXT_WHOLESALE_COST BINARY_DOUBLE,WS_EXT_LIST_PRICE BINARY_DOUBLE,WS_EXT_TAX BINARY_DOUBLE,WS_COUPON_AMT BINARY_DOUBLE,WS_EXT_SHIP_COST BINARY_DOUBLE,WS_NET_PAID BINARY_DOUBLE,WS_NET_PAID_INC_TAX BINARY_DOUBLE,WS_NET_PAID_INC_SHIP BINARY_DOUBLE,WS_NET_PAID_INC_SHIP_TAX BINARY_DOUBLE,WS_NET_PROFIT BINARY_DOUBLE)
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/web_sales/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE item
  (I_ITEM_SK NUMBER(19,0),I_ITEM_ID VARCHAR2(4000 BYTE),I_REC_START_DATE VARCHAR2(4000 BYTE),I_REC_END_DATE VARCHAR2(4000 BYTE),I_ITEM_DESC VARCHAR2(4000 BYTE),I_CURRENT_PRICE BINARY_DOUBLE,I_WHOLESALE_COST BINARY_DOUBLE,I_BRAND_ID NUMBER(19,0),I_BRAND VARCHAR2(4000 BYTE),I_CLASS_ID NUMBER(19,0),I_CLASS VARCHAR2(4000 BYTE),I_CATEGORY_ID NUMBER(19,0),I_CATEGORY VARCHAR2(4000 BYTE),I_MANUFACT_ID NUMBER(19,0),I_MANUFACT VARCHAR2(4000 BYTE),I_SIZE VARCHAR2(4000 BYTE),I_FORMULATION VARCHAR2(4000 BYTE),I_COLOR VARCHAR2(4000 BYTE),I_UNITS VARCHAR2(4000 BYTE),I_CONTAINER VARCHAR2(4000 BYTE),I_MANAGER_ID NUMBER(19,0),I_PRODUCT_NAME VARCHAR2(4000 BYTE))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/item/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE store_returns
  (SR_RETURNED_DATE_SK NUMBER(19,0),SR_RETURN_TIME_SK NUMBER(19,0),SR_ITEM_SK NUMBER(19,0),SR_CUSTOMER_SK NUMBER(19,0),SR_CDEMO_SK NUMBER(19,0),SR_HDEMO_SK NUMBER(19,0),SR_ADDR_SK NUMBER(19,0),SR_STORE_SK NUMBER(19,0),SR_REASON_SK NUMBER(19,0),SR_TICKET_NUMBER NUMBER(19,0),SR_RETURN_QUANTITY NUMBER(19,0),SR_RETURN_AMT BINARY_DOUBLE,SR_RETURN_TAX BINARY_DOUBLE,SR_RETURN_AMT_INC_TAX BINARY_DOUBLE,SR_FEE BINARY_DOUBLE,SR_RETURN_SHIP_COST BINARY_DOUBLE,SR_REFUNDED_CASH BINARY_DOUBLE,SR_REVERSED_CHARGE BINARY_DOUBLE,SR_STORE_CREDIT BINARY_DOUBLE,SR_NET_LOSS BINARY_DOUBLE)
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/store_returns/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE store
  (S_STORE_SK NUMBER(19,0),S_STORE_ID VARCHAR2(4000 BYTE),S_REC_START_DATE VARCHAR2(4000 BYTE),S_REC_END_DATE VARCHAR2(4000 BYTE),S_CLOSED_DATE_SK NUMBER(19,0),S_STORE_NAME VARCHAR2(4000 BYTE),S_NUMBER_EMPLOYEES NUMBER(19,0),S_FLOOR_SPACE NUMBER(19,0),S_HOURS VARCHAR2(4000 BYTE),S_MANAGER VARCHAR2(4000 BYTE),S_MARKET_ID NUMBER(19,0),S_GEOGRAPHY_CLASS VARCHAR2(4000 BYTE),S_MARKET_DESC VARCHAR2(4000 BYTE),S_MARKET_MANAGER VARCHAR2(4000 BYTE),S_DIVISION_ID NUMBER(19,0),S_DIVISION_NAME VARCHAR2(4000 BYTE),S_COMPANY_ID NUMBER(19,0),S_COMPANY_NAME VARCHAR2(4000 BYTE),S_STREET_NUMBER NUMBER(19,0),S_STREET_NAME VARCHAR2(4000 BYTE),S_STREET_TYPE VARCHAR2(4000 BYTE),S_SUITE_NUMBER VARCHAR2(4000 BYTE),S_CITY VARCHAR2(4000 BYTE),S_COUNTY VARCHAR2(4000 BYTE),S_STATE VARCHAR2(4000 BYTE),S_ZIP NUMBER(19,0),S_COUNTRY VARCHAR2(4000 BYTE),S_GMT_OFFSET NUMBER(19,0),S_TAX_PRECENTAGE BINARY_DOUBLE)
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/store/*')
  )  REJECT LIMIT UNLIMITED;

CREATE TABLE customer_address
  (CA_ADDRESS_SK NUMBER(19,0),CA_ADDRESS_ID VARCHAR2(4000 BYTE),CA_STREET_NUMBER NUMBER(19,0),CA_STREET_NAME VARCHAR2(4000 BYTE),CA_STREET_TYPE VARCHAR2(4000 BYTE),CA_SUITE_NUMBER VARCHAR2(4000 BYTE),CA_CITY VARCHAR2(4000 BYTE),CA_COUNTY VARCHAR2(4000 BYTE),CA_STATE VARCHAR2(4000 BYTE),CA_ZIP NUMBER(19,0),CA_COUNTRY VARCHAR2(4000 BYTE),CA_GMT_OFFSET NUMBER(19,0),CA_LOCATION_TYPE VARCHAR2(4000 BYTE))
  ORGANIZATION EXTERNAL
  (TYPE ORACLE_BIGDATA
   ACCESS PARAMETERS
   (
     com.oracle.bigdata.debug=TRUE
     com.oracle.bigdata.credential.name=OBJ_STORE_CRED
     com.oracle.bigdata.fileformat=textfile
    com.oracle.bigdata.csv.rowformat.fields.terminator = '|'
   )
   location ('https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/oraclebigdatadb/tpcds_csv/customer_address/*')
  )  REJECT LIMIT UNLIMITED;

